### ISSUE TITLE
As the owner, I want to keep track of the amount of beer that was consumed and how much there is left, because it allows me to accuratly predict the future

### ISSUE THREAD

**Issue by brian-vdb** [brian-vdb/vrijtap#3]

**Comment by benjamin-kelada** [comment]
- find out which method is best to keep track of the beer consumed.
- test the method with a prototype to see if it is functional for this product.

**Comment by Diego-Brandjes** [comment]
- Make a system that can measure the amount of fluid left in the source
- Make a system that can use the data to make a prediction about beer consumption
